#!/usr/bin/env python3

import argparse
import sys


def main(day, year, slow):
    try:
        solver = __import__(
            f"solutions.{year}.code.day_{day}", fromlist=["Solution"]
        ).Solution
    except ImportError:
        print(f"solution not found for day {day} ({year})")
        sys.exit(1)

    solver(slow).print_solutions()


PARSER = argparse.ArgumentParser(
    description="Run a day of Advent of Code", prog="advent"
)

PARSER.add_argument("day", type=int)
PARSER.add_argument("--year", default=2019, type=int)
PARSER.add_argument("--slow", action="store_true")

ARGS = PARSER.parse_args()
main(ARGS.day, ARGS.year, ARGS.slow)
