#!/usr/bin/env python3

import sys

USAGE = "usage: advent <day> [year]"


def main(day, year):
    try:
        solver = __import__(
            f"solutions.{year}.code.day_{day}", fromlist=["Solution"]
        ).Solution
    except ImportError as e:
        print(f"solution not found for day {day} ({year})\n\t--{e}")
        sys.exit(1)

    s = solver(day)
    s.print_solutions()


if len(sys.argv) < 2 or len(sys.argv) > 3:
    print(USAGE)
    exit(1)
else:
    try:
        day_num = int(sys.argv[1])
    except ValueError:
        print("ERR: day must be a number")
        print(USAGE)
        exit(1)

    year = sys.argv[2] if len(sys.argv) == 3 else 2018
    main(day_num, year)
