select = ["E", "F", "I001"]


ignore = [
  "E501", # skip enforcing line length
  "E741", # ignore short variable names
]

unfixable = [
  "F401", # don't remove unused imports
  "F841", # don't remove unused variables
]
