#!/bin/bash
NUM=$1
YEAR=${2-2018}
DESCRIPTION="# prompt: https://adventofcode.com/${YEAR}/day"

if [[ -z "$NUM" ]]; then
  echo "USAGE: ./start number [year]"
  exit 1
fi

touch "solutions/${YEAR}/inputs/$1.txt" # this is safe either way

if [[ -e "solutions/${YEAR}/code/day_$1.py" ]];then
  echo 'skipping solution creation, file already exists'
else
  echo -e "$DESCRIPTION/$1\n\n$(cat example_solution.py)" > "solutions/${YEAR}/code/day_$1.py"
  echo "Created Files for Day $1 (${YEAR})"
fi
