#!/usr/bin/env python3

import argparse
from pathlib import Path

from _date_utils import current_puzzle_year

PARSER = argparse.ArgumentParser(
    prog="./start", description="Start a new Advent of Code solution"
)
PARSER.add_argument("day", type=int, help="Which puzzle day to start, between [1,25]")
PARSER.add_argument("--year", default=current_puzzle_year(), help="Puzzle year")
ARGS = PARSER.parse_args()

if ARGS.day < 1 or ARGS.day > 25:
    PARSER.error("day must be in [1,25]")

day_dir = Path(f"solutions/{ARGS.year}/day_{ARGS.day}")

day_dir.mkdir(parents=True, exist_ok=True)
Path(day_dir, "__init__.py").touch()
Path(day_dir, "input.txt").touch()
Path(day_dir, "README.md").touch()

solution_path = Path(day_dir, "solution.py")
if solution_path.exists():
    print("skipping solution creation, files already exists")
else:
    template = Path("example_solution.py.tmpl").read_text()
    replaced_template = template.replace("<YEAR>", ARGS.year).replace(
        "<DAY>", str(ARGS.day)
    )
    solution_path.write_text(replaced_template)
